"""Freeze a trained TI-A into constants that a non-learning port can evaluate.

TradingView's Pine Script cannot learn. It has no cross-session persistence, no
optimiser, no way to accumulate an Edge Book across a universe of instruments,
and no way to fit an isotonic map. Everything in ``docs/01-THEORY.md`` that
depends on *estimation* therefore has to happen here, in Python, once; the port
only *evaluates*.

That split is not a compromise forced by the platform. It is the same split the
architecture already has: ``Provenance.DEV`` parameters are fit once on the
development universe and then frozen (``config.py``), and ``Provenance.ONLINE``
quantities are causal recursions that a streaming port can reproduce exactly.
This module writes out the first group -- plus the two learned objects, the Edge
Book posteriors and the calibration map -- as a single JSON manifest.

What is exported, and why each item is here:

``engines.correlation`` / ``engines.precision``
    The causally-estimated engine correlation matrix ``C`` from
    :class:`tia.fusion.calop.CALOP`, ridge-regularised by ``fusion_shrink``, and
    its inverse. Pine consumes ``C^-1`` directly so it never has to invert a
    matrix for the *total* breadth; the reliability scaling
    ``M = D^(1/2) C^-1 D^(1/2)`` stays live because reliabilities change every
    bar. The un-inverted ``C`` is also exported because the *aligned* breadth of
    :meth:`CALOP.fuse` needs a principal sub-matrix inverted at runtime.

``fusion.temperature`` / ``bias`` / ``evidence_sd``
    The three ``DEV`` parameters of §6.3. Frozen by definition.

``calibration.knots_x`` / ``knots_y``
    :meth:`IsotonicCalibrator.knots` -- the piecewise-linear monotone map fitted
    by PAVA on resolved outcomes. Pine interpolates it with the same linear rule
    ``numpy.interp`` uses.

``regime.tempering_exponent``
    ``eta = EBE_f / J`` of §5.3. Python re-estimates this every bar from a
    rolling 8x8 feature correlation; Pine takes the frozen value, because an
    8x8 correlation plus inverse per bar is not worth its cost for a quantity
    that moves this slowly. The realised dispersion of ``eta`` over the training
    run is exported alongside it so the approximation error is auditable.

``edge_book.cells``
    For every one of the ``4 x 4 x n_buckets`` leaves, the *hierarchically
    shrunk* Normal-Inverse-Gamma posterior: ``mu_n``, the Student-t ``scale``,
    ``dof`` and the effective count ``n_eff``. Pine reconstructs
    ``LCB_q = mu_n + t_{q,dof} * scale`` with the same Cornish-Fisher expansion
    :func:`tia.engines.edgebook.student_t_ppf` uses, so the two ports agree to
    the accuracy of that expansion and not to the accuracy of a table lookup.

Round-tripping is checked: :func:`export_frozen_model` recomputes every exported
lower credible bound from the exported triple and asserts agreement with the
Edge Book's own number.

The companion function :func:`emit_pine_constants` transpiles the manifest into
the ``BEGIN/END FROZEN MODEL`` region of the ``.pine`` files. Pine cannot read
files or parse JSON at runtime, so vectors and matrices become comma-separated
string literals that the script splits once on its first bar.
"""

from __future__ import annotations

import datetime as _dt
import json
import math
import sys
import re
import pathlib
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np

from .config import Config, Provenance
from .engines.edgebook import EdgeBook, SetupFamily, student_t_ppf
from .engines.regime import DESIGN, FEATURE_ORDER
from .fusion.calibration import IsotonicCalibrator
from .types import REGIME_NAMES, Regime

__all__ = [
    "SCHEMA_VERSION",
    "PINE_ENGINE_ORDER",
    "PINE_BEGIN_MARKER",
    "PINE_END_MARKER",
    "export_frozen_model",
    "emit_pine_constants",
    "train_reference_system",
    "main",
]

#: Bump the minor when a field is added, the major when one changes meaning.
#: ``TIA.pine`` refuses to run against a schema it was not written for.
SCHEMA_VERSION = "2.0.0"

#: The engines the Pine port implements, in the order its arrays are indexed.
#: ``crossasset`` needs an :class:`~tia.types.ExogenousSnapshot` (peer returns,
#: an implied-volatility level) that a single-symbol Pine script does not have,
#: and ``positioning`` is ``enable_positioning_engine=False`` by default because
#: public dealer-gamma estimates are not verifiable. Both are excluded rather
#: than stubbed, so that the correlation matrix Pine pools against is the matrix
#: of the engines Pine actually runs.
PINE_ENGINE_ORDER: tuple[str, ...] = (
    "regime",
    "trend",
    "momentum",
    "liquidity",
    "volatility",
    "structure",
    "behavioral",
)

PINE_BEGIN_MARKER = "// ==== BEGIN FROZEN MODEL (generated by tia.export) ===="
PINE_END_MARKER = "// ==== END FROZEN MODEL (generated by tia.export) ===="

#: Rounding used for every exported float. Twelve significant digits is far more
#: than the estimation error of anything here and keeps the JSON diffable.
_SIG = 12


def _r(x: float) -> float | None:
    """Round a scalar for export. Missing becomes JSON ``null``, not a number.

    NaN previously mapped to ``-1e15``, because ``nan > 0`` is False. That is the
    worst possible encoding for a *missing* value: it is finite, plausible, and a
    consumer has no way to tell it apart from a real measurement. A calibration
    Brier score of -1e15 was reaching the exported manifest.

    True infinities keep a magnitude sentinel because they carry a direction and
    a meaning (an untradeable cost, for instance), and that meaning is worth
    preserving.
    """
    v = float(x)
    if v != v:
        return None
    if not math.isfinite(v):
        return 1e15 if v > 0 else -1e15
    return float(f"%.{_SIG}g" % v)


def _rv(xs: Iterable[float]) -> list[float]:
    """Round a vector. Vectors are consumed numerically by the port, so a
    non-finite entry is a defect rather than a value and is raised loudly."""
    out: list[float] = []
    for i, x in enumerate(xs):
        v = float(x)
        if not math.isfinite(v):
            raise ValueError(
                f"non-finite value {v!r} at index {i} of an exported vector; "
                "the port consumes these numerically and cannot represent it"
            )
        out.append(float(f"%.{_SIG}g" % v))
    return out


def _rm(m: Sequence[Sequence[float]]) -> list[list[float]]:
    return [[_r(x) for x in row] for row in m]


# ---------------------------------------------------------------------------
# Blocks
# ---------------------------------------------------------------------------


def _log_beta_norm(a: float, b: float) -> float:
    """``ln B(a, b)`` -- the term :func:`tia.engines.regime.beta_logpdf` subtracts.

    Exported per cell because Pine has no log-gamma function and the shapes are
    frozen, so the whole normalising constant is a compile-time number there.
    """
    return math.lgamma(a) + math.lgamma(b) - math.lgamma(a + b)


def _regime_block(cfg: Config, temper: float, temper_sd: float, temper_n: int) -> dict[str, Any]:
    """The §5.2 measurement design, expanded into shapes Pine can use directly."""
    c = cfg.regime_beta_concentration
    a = np.ones((4, len(FEATURE_ORDER)))
    b = np.ones((4, len(FEATURE_ORDER)))
    m = np.full((4, len(FEATURE_ORDER)), 0.5)
    claims = np.zeros((4, len(FEATURE_ORDER)), dtype=int)
    for reg, row in DESIGN.items():
        for j, mv in enumerate(row):
            if mv is None:
                # Beta(1, 1) is exactly uniform: "this regime makes no claim
                # about this feature" contributes a likelihood factor of one and
                # lives inside the same parametric family. Theory §5.2.
                a[int(reg), j] = 1.0
                b[int(reg), j] = 1.0
                m[int(reg), j] = 0.5
                claims[int(reg), j] = 0
            else:
                a[int(reg), j] = max(mv * c, 1e-3)
                b[int(reg), j] = max((1.0 - mv) * c, 1e-3)
                m[int(reg), j] = mv
                claims[int(reg), j] = 1
    lognorm = np.array(
        [[_log_beta_norm(float(a[k, j]), float(b[k, j])) for j in range(a.shape[1])] for k in range(4)]
    )
    s = float(min(max(cfg.regime_stickiness, 0.5), 0.9999))
    return {
        "n_regimes": 4,
        "names": list(REGIME_NAMES),
        "feature_order": list(FEATURE_ORDER),
        "beta_concentration": _r(c),
        "design_m": _rm(m.tolist()),
        "design_makes_claim": claims.tolist(),
        "design_a": _rm(a.tolist()),
        "design_b": _rm(b.tolist()),
        "design_log_beta_norm": _rm(lognorm.tolist()),
        "stickiness": _r(s),
        "log_stay": _r(math.log(s)),
        "log_switch": _r(math.log((1.0 - s) / 3.0)),
        "tempering_exponent": _r(temper),
        "tempering_exponent_sd": _r(temper_sd),
        "tempering_exponent_samples": int(temper_n),
        "tempering_note": (
            "eta = EBE_f / J of THEORY 5.3, frozen. Python re-estimates it every "
            "bar from a rolling 8x8 feature correlation; the port takes the "
            "training-run median. tempering_exponent_sd bounds the resulting "
            "posterior error -- see docs/11-PINE-PLAN.md."
        ),
        "min_usable_features": 4,
        "feature_eps": 1e-6,
        "hazard_halflife_bars": _r(cfg.regime_shift_hazard_halflife),
        "hazard_max": _r(cfg.regime_hazard_max),
    }


def _engine_block(
    system: Any, cfg: Config, correlation: np.ndarray | None = None, source: str = ""
) -> dict[str, Any]:
    """Engine correlation structure, restricted to the engines the port runs."""
    names = list(getattr(system.calop, "names", PINE_ENGINE_ORDER))
    missing = [n for n in PINE_ENGINE_ORDER if n not in names]
    if missing:
        raise ValueError(f"trained system has no engine named {missing}")

    if correlation is not None:
        # A correlation estimated over exactly the ported engines. Preferred,
        # because CALOP.observe only feeds its estimator on bars where *every*
        # engine is valid -- and `crossasset` and `positioning` never are
        # without exogenous data, so the system's own estimate never leaves its
        # 0.35-everywhere cold-start prior. Exporting that prior as if it were
        # measured would be a lie of exactly the kind §6.4 warns about.
        c = np.asarray(correlation, dtype=np.float64)
        src = source or "measured over the ported engines during the export replay"
    else:
        idx = [names.index(n) for n in PINE_ENGINE_ORDER]
        # A principal sub-matrix of a ridge-regularised correlation matrix is
        # still positive definite, so restricting to the ported engines is safe.
        c = np.asarray(system.calop.correlation(), dtype=np.float64)[np.ix_(idx, idx)]
        src = source or "principal sub-matrix of CALOP.correlation()"
    cinv = np.linalg.inv(c)
    m = c.shape[0]
    ones = np.ones(m)
    off = c[~np.eye(m, dtype=bool)]
    return {
        "order": list(PINE_ENGINE_ORDER),
        "count": m,
        "correlation_source": src,
        "excluded": ["crossasset", "positioning"],
        "excluded_reason": (
            "crossasset requires ExogenousSnapshot peers/implied vol; positioning "
            "is enable_positioning_engine=False by default (config.py)."
        ),
        "correlation": _rm(c.tolist()),
        "precision": _rm(cinv.tolist()),
        "fusion_shrink": _r(cfg.fusion_shrink),
        "ebe_at_unit_reliability": _r(float(ones @ cinv @ ones)),
        "mean_abs_offdiag": _r(float(np.mean(np.abs(off))) if off.size else 0.0),
        "max_abs_offdiag": _r(float(np.max(np.abs(off))) if off.size else 0.0),
        "condition_number": _r(float(np.linalg.cond(c))),
        "warmup": {
            e.name: int(getattr(e, "warmup", 0))
            for e in system.engines
            if e.name in PINE_ENGINE_ORDER
        },
    }


def _calibration_block(cal: IsotonicCalibrator, cfg: Config, n_outcomes: int, health: dict[str, float]) -> dict[str, Any]:
    knots = cal.knots()
    xs = [k[0] for k in knots]
    ys = [k[1] for k in knots]
    return {
        "temperature": _r(cfg.fusion_temperature),
        "bias": _r(cfg.fusion_bias),
        "evidence_sd": _r(cfg.fusion_evidence_sd),
        "score_clamp": 0.999,
        "align_eps": 0.05,
        "credible_z": _r(1.6448536269514722),
        "isotonic_enabled": bool(cal.n_fit > 0),
        "isotonic_n_fit": int(cal.n_fit),
        "knots_x": _rv(xs),
        "knots_y": _rv(ys),
        "n_knots": len(xs),
        "min_samples": int(cfg.calibration_min_samples),
        "n_outcomes": int(n_outcomes),
        "brier": _r(health.get("brier", float("nan"))) if health else None,
        "ece": _r(health.get("ece", float("nan"))) if health else None,
        "interpolation": "linear between knots, clamped at the ends (numpy.interp semantics)",
    }


def _edge_block(book: EdgeBook, cfg: Config) -> dict[str, Any]:
    """Every leaf posterior, already shrunk through the three-level hierarchy."""
    n_b = int(cfg.edge_evidence_buckets)
    setups = [s.name.lower() for s in SetupFamily]
    mu, scale, dof, n_eff, lcb, ucb, out_var, var_mu = [], [], [], [], [], [], [], []
    names: list[str] = []
    q = float(cfg.edge_lcb_quantile)

    for k in range(4):
        for s in range(len(setups)):
            for b in range(n_b):
                est = book.estimate(k, s, b)
                # The Student-t scale is sqrt(b_n / (a_n kappa_n)); EdgeEstimate
                # reports var_mean = scale^2 * dof/(dof-2), and a_n >= a0 = 3 by
                # construction so dof > 2 always and the inversion is exact.
                sc = math.sqrt(max(est.var_mean * (est.dof - 2.0) / est.dof, 0.0))
                mu.append(est.mean)
                scale.append(sc)
                dof.append(est.dof)
                n_eff.append(est.n_eff)
                lcb.append(est.lcb)
                ucb.append(est.ucb)
                out_var.append(est.outcome_var)
                var_mu.append(est.var_mean)
                names.append(f"{REGIME_NAMES[k]}/{setups[s]}/b{b}")

    # Round trip: Pine will rebuild the bound from (mu_n, scale, dof). If that
    # does not reproduce the Edge Book's own lcb here, the port cannot either.
    worst = 0.0
    for i in range(len(mu)):
        rebuilt = mu[i] + student_t_ppf(q, dof[i]) * scale[i]
        worst = max(worst, abs(rebuilt - lcb[i]))
    if worst > 1e-9:
        raise AssertionError(f"lower-bound round trip failed by {worst:.3e} sigma")

    return {
        "setups": setups,
        "setup_priority": ["sweep_reversal", "compression_break", "range_fade", "continuation"],
        "n_setups": len(setups),
        "n_buckets": n_b,
        "bucket_edges": [0.25, 0.6, 1.0, 1.6][: max(n_b - 1, 0)],
        "bucket_source": "abs(pooled log-odds L)",
        "lcb_quantile": _r(q),
        "prior": {
            "mu0": _r(cfg.edge_prior_mean_sigma),
            "kappa0": _r(cfg.edge_prior_strength),
            "pooling_strength": _r(cfg.edge_pooling_strength),
            "a0": _r(book.a0),
            "b0": _r(book.b0),
        },
        "halflife_bars": _r(cfg.edge_halflife_bars),
        "cell_index": "idx = (regime * n_setups + setup) * n_buckets + bucket",
        "n_cells": len(mu),
        "cell_names": names,
        "lcb_round_trip_max_abs_error": _r(worst),
        "cells": {
            "mu_n": _rv(mu),
            "scale": _rv(scale),
            "dof": _rv(dof),
            "n_eff": _rv(n_eff),
            "outcome_var": _rv(out_var),
            "var_mean": _rv(var_mu),
            "lcb": _rv(lcb),
            "ucb": _rv(ucb),
        },
    }


def _feature_block(cfg: Config) -> dict[str, Any]:
    # Mirrors FeatureKernel.warmup so the port marks itself valid on the same bar.
    warmup = max(
        max(cfg.vol_window_long, 30) + 2,   # VolatilityKernel.warmup
        70,                                  # MicrostructureKernel.warmup
        cfg.rank_min_obs + 10,
        cfg.vr_window // 2,
        cfg.htf_multiple_2 * 4,
    )
    return {
        "warmup_bars": int(warmup),
        "vol_window": cfg.vol_window,
        "vol_window_short": cfg.vol_window_short,
        "vol_window_long": cfg.vol_window_long,
        "ewma_halflife": _r(cfg.ewma_halflife),
        "har_weights": _rv(cfg.har_weights),
        "rank_window": cfg.rank_window,
        "rank_min_obs": cfg.rank_min_obs,
        "vov_window": 60,
        "impact_exponent": _r(cfg.impact_exponent),
        "participation_window": cfg.participation_window,
        "tod_buckets": cfg.tod_buckets,
        "clv_halflife": 5.0,
        "spread_estimator_window": cfg.spread_estimator_window,
        "vr_window": cfg.vr_window,
        "vr_lags": list(cfg.vr_lags),
        "perm_entropy_order": cfg.perm_entropy_order,
        "perm_entropy_window": cfg.perm_entropy_window,
        "efficiency_window": cfg.vol_window,
        "agreement_horizons": [5, 10, 20, 40, 80],
        "pivot_atr_mult": _r(cfg.pivot_atr_mult),
        "pivot_confirm_bars": cfg.pivot_confirm_bars,
        "htf_multiple": cfg.htf_multiple,
        "htf_multiple_2": cfg.htf_multiple_2,
        "sweep_max_bars_to_reclaim": 6,
        "sweep_min_penetration_sigma": 0.25,
        "sweep_participation_rank_min": 0.75,
        "kalman_snr": _r(cfg.kalman_snr),
        "kalman_slope_snr": _r(cfg.kalman_slope_snr),
        "not_ported": {
            "sigma_gk": "Garman-Klass is computed by VolReadout but never copied into FeatureSnapshot, so no engine reads it.",
            "amihud / kyle_lambda": "diagnostics only; no engine or gate reads them.",
            "run_asym / ret_kurtosis": "present in FeatureSnapshot, read by no engine.",
            "delta_norm": "requires a footprint feed (Bar.delta); unavailable on TradingView OHLCV.",
            "htf2": "FeatureKernel updates the 25x view but never copies it into the snapshot.",
        },
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def export_frozen_model(
    system: Any,
    path: str | Path,
    *,
    dev_universe: dict[str, Any] | None = None,
    training: dict[str, Any] | None = None,
    tempering: tuple[float, float, int] | None = None,
    engine_correlation: np.ndarray | None = None,
    correlation_source: str = "",
) -> dict[str, Any]:
    """Write the frozen manifest for ``system`` to ``path`` and return it.

    ``system`` is a trained :class:`tia.pipeline.TIA`: its ``edge_book`` holds
    observed outcomes, its ``calibrator`` holds a fitted isotonic map (or does
    not, in which case the port falls back to the parametric link), and its
    ``calop`` has seen enough bars for the engine correlation estimate to be the
    measured one rather than the 0.35-everywhere cold-start prior.

    ``tempering`` optionally supplies ``(median, sd, n)`` for the regime
    tempering exponent measured over the training run. Without it the exporter
    falls back to the engine's last value, which is a sample of one.
    """
    cfg: Config = system.cfg
    cal = getattr(system.calibrator, "_iso", None) or IsotonicCalibrator()
    health = {}
    try:
        health = system.calibrator.health()
    except Exception:  # pragma: no cover - health is best-effort metadata
        health = {}

    if tempering is None:
        t_med = float(getattr(system.regime_engine.state, "temper", 1.0))
        tempering = (t_med, 0.0, 1)
    t_med, t_sd, t_n = tempering

    model: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat(),
        "generator": "tia.export.export_frozen_model",
        "tia_version": cfg.version,
        "config_manifest_hash": cfg.manifest_hash(),
        "is_placeholder": False,
        "fitted_dof": cfg.fitted_dof(),
        "online_dof": cfg.online_dof(),
        "dev_universe": dev_universe or {},
        "training": training or {},
        "features": _feature_block(cfg),
        "regime": _regime_block(cfg, t_med, t_sd, t_n),
        "engines": _engine_block(system, cfg, engine_correlation, correlation_source),
        "fusion": _calibration_block(cal, cfg, int(getattr(system.calibrator, "n_samples", 0)), health),
        "edge_book": _edge_block(system.edge_book, cfg),
        "barriers": {
            "stop_sigma": _r(cfg.stop_sigma),
            "target_sigma": _r(cfg.target_sigma),
            "max_holding_bars": int(cfg.max_holding_bars),
            "min_holding_bars": int(cfg.min_holding_bars),
            "execution_lag_bars": int(cfg.execution_lag_bars),
        },
        "costs": {
            "impact_eta": _r(cfg.cost_impact_eta),
            "slippage_range_frac": _r(cfg.cost_slippage_range_frac),
            "fee_bps": _r(cfg.cost_fee_bps),
            "default_participation": _r(cfg.default_participation),
            "max_half_spread_sigma": _r(cfg.cost_max_half_spread_sigma),
            "spread_fallback_rel": 5e-4,
            "formula": "round_trip = 2 * (k*(S/2)/sigma + k*eta*sqrt(q) + k*phi*min(range/sigma,5) + fee/sigma), k = 1 + 1.5*p_stress",
        },
        "gate": {
            "ev_lcb_min_sigma": _r(cfg.ev_lcb_min_sigma),
            "p_min": _r(cfg.p_min),
            "p_exit": _r(cfg.p_exit),
            "ebe_min": _r(cfg.ebe_min),
            "regime_hazard_max": _r(cfg.regime_hazard_max),
            "max_trades_per_100_bars": _r(cfg.max_trades_per_100_bars),
            "allow_shorts": bool(cfg.allow_shorts),
        },
        "risk": {
            "kelly_fraction": _r(cfg.kelly_fraction),
            "risk_per_trade": _r(cfg.risk_per_trade),
            "max_risk_per_trade": _r(cfg.max_risk_per_trade),
            "dd_throttle_start": _r(cfg.dd_throttle_start),
            "dd_throttle_stop": _r(cfg.dd_throttle_stop),
            "dd_throttle_floor": _r(cfg.dd_throttle_floor),
            "dd_kill": _r(cfg.dd_kill),
        },
        "provenance": {
            p.value: {k: (list(v) if isinstance(v, tuple) else v) for k, v in cfg.by_provenance(p).items()}
            for p in Provenance
        },
        "pine": {
            "target_files": ["pine/TIA.pine", "pine/TIA_strategy.pine"],
            "begin_marker": PINE_BEGIN_MARKER,
            "end_marker": PINE_END_MARKER,
            "representation": (
                "Vectors and matrices become comma-separated string literals, "
                "row-major, split once on the first bar. Pine cannot read files "
                "or parse JSON at runtime."
            ),
        },
    }

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(model, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    return model


# ---------------------------------------------------------------------------
# Pine emitter
# ---------------------------------------------------------------------------


def _pine_num(x: float | None) -> str:
    """Render one number for Pine. Missing becomes ``na``, which Pine understands
    and propagates correctly; a magnitude sentinel would be silently arithmetic."""
    if x is None:
        return "na"
    v = float(x)
    if v != v:
        return "na"
    if not math.isfinite(v):
        v = 1e15 if v > 0 else -1e15
    return f"{v:.10g}"


def _pine_csv(values: Sequence[float]) -> str:
    return ",".join(_pine_num(v) for v in values)


def _pine_csv_matrix(m: Sequence[Sequence[float]]) -> str:
    return ",".join(_pine_num(v) for row in m for v in row)


def _pine_region(model: dict[str, Any]) -> str:
    """Render the generated constant region. Row-major throughout."""
    reg = model["regime"]
    eng = model["engines"]
    fus = model["fusion"]
    eb = model["edge_book"]
    ft = model["features"]
    ba = model["barriers"]
    co = model["costs"]
    ga = model["gate"]
    ri = model["risk"]
    cells = eb["cells"]

    L: list[str] = [PINE_BEGIN_MARKER]
    a = L.append
    a("// Do not hand-edit. Regenerate with:")
    a("//   python -m tia.export --out pine/frozen_model.json --emit pine/TIA.pine pine/TIA_strategy.pine")
    a(f"// schema {model['schema_version']}   generated {model['generated_at']}")
    a(f"// config manifest {model['config_manifest_hash']}   placeholder={str(model['is_placeholder']).lower()}")
    a("")
    a(f'FM_SCHEMA        = "{model["schema_version"]}"')
    a(f'FM_HASH          = "{model["config_manifest_hash"]}"')
    a(f'FM_GENERATED     = "{model["generated_at"]}"')
    a(f'FM_PLACEHOLDER   = {str(bool(model["is_placeholder"])).lower()}')
    a("")
    a("// --- feature kernel ---------------------------------------------------")
    a(f"FM_WARMUP        = {int(ft['warmup_bars'])}")
    a(f"FM_VOL_N         = {int(ft['vol_window'])}")
    a(f"FM_VOL_NS        = {int(ft['vol_window_short'])}")
    a(f"FM_VOL_NL        = {int(ft['vol_window_long'])}")
    a(f"FM_EWMA_HL       = {_pine_num(ft['ewma_halflife'])}")
    a(f"FM_HAR_D         = {_pine_num(ft['har_weights'][0])}")
    a(f"FM_HAR_W         = {_pine_num(ft['har_weights'][1])}")
    a(f"FM_HAR_M         = {_pine_num(ft['har_weights'][2])}")
    a(f"FM_RANK_N        = {int(ft['rank_window'])}")
    a(f"FM_RANK_MIN      = {int(ft['rank_min_obs'])}")
    a(f"FM_VOV_N         = {int(ft['vov_window'])}")
    a(f"FM_PSI           = {_pine_num(ft['impact_exponent'])}")
    a(f"FM_PART_N        = {int(ft['participation_window'])}")
    a(f"FM_TOD_BUCKETS   = {int(ft['tod_buckets'])}")
    a(f"FM_CLV_HL        = {_pine_num(ft['clv_halflife'])}")
    a(f"FM_SPREAD_N      = {int(ft['spread_estimator_window'])}")
    a(f"FM_VR_N          = {int(ft['vr_window'])}")
    a(f'FM_VR_LAGS       = "{",".join(str(int(q)) for q in ft["vr_lags"])}"')
    a(f"FM_PE_ORDER      = {int(ft['perm_entropy_order'])}")
    a(f"FM_PE_N          = {int(ft['perm_entropy_window'])}")
    a(f"FM_EFF_N         = {int(ft['efficiency_window'])}")
    a(f'FM_AGREE_H       = "{",".join(str(int(h)) for h in ft["agreement_horizons"])}"')
    a(f"FM_PIV_MULT      = {_pine_num(ft['pivot_atr_mult'])}")
    a(f"FM_PIV_CONFIRM   = {int(ft['pivot_confirm_bars'])}")
    a(f"FM_HTF_MULT      = {int(ft['htf_multiple'])}")
    a(f"FM_SWEEP_MAXBARS = {int(ft['sweep_max_bars_to_reclaim'])}")
    a(f"FM_SWEEP_MINPEN  = {_pine_num(ft['sweep_min_penetration_sigma'])}")
    a(f"FM_SWEEP_PARTMIN = {_pine_num(ft['sweep_participation_rank_min'])}")
    a(f"FM_KAL_SNR       = {_pine_num(ft['kalman_snr'])}")
    a(f"FM_KAL_SNR_SLOPE = {_pine_num(ft['kalman_slope_snr'])}")
    a("")
    a("// --- regime measurement model (THEORY 5.2), row-major 4 regimes x 8 features")
    a(f'FM_RG_FEATURES   = "{",".join(reg["feature_order"])}"')
    a(f'FM_RG_NAMES      = "{",".join(reg["names"])}"')
    a(f'FM_RG_A          = "{_pine_csv_matrix(reg["design_a"])}"')
    a(f'FM_RG_B          = "{_pine_csv_matrix(reg["design_b"])}"')
    a(f'FM_RG_LOGNORM    = "{_pine_csv_matrix(reg["design_log_beta_norm"])}"')
    a(f"FM_RG_LOG_STAY   = {_pine_num(reg['log_stay'])}")
    a(f"FM_RG_LOG_SWITCH = {_pine_num(reg['log_switch'])}")
    a(f"FM_RG_TEMPER     = {_pine_num(reg['tempering_exponent'])}")
    a(f"FM_RG_TEMPER_SD  = {_pine_num(reg['tempering_exponent_sd'])}")
    a(f"FM_RG_HAZ_HL     = {_pine_num(reg['hazard_halflife_bars'])}")
    a(f"FM_RG_HAZ_MAX    = {_pine_num(reg['hazard_max'])}")
    a(f"FM_RG_MIN_FEAT   = {int(reg['min_usable_features'])}")
    a("")
    a("// --- fusion (CALOP, THEORY 6) ----------------------------------------")
    a(f'FM_ENG_NAMES     = "{",".join(eng["order"])}"')
    a(f"FM_ENG_M         = {int(eng['count'])}")
    a(f'FM_ENG_CORR      = "{_pine_csv_matrix(eng["correlation"])}"')
    a(f'FM_ENG_PREC      = "{_pine_csv_matrix(eng["precision"])}"')
    a(f"FM_ENG_EBE_UNIT  = {_pine_num(eng['ebe_at_unit_reliability'])}")
    a(f"FM_FUSE_T        = {_pine_num(fus['temperature'])}")
    a(f"FM_FUSE_B        = {_pine_num(fus['bias'])}")
    a(f"FM_FUSE_SD       = {_pine_num(fus['evidence_sd'])}")
    a(f"FM_FUSE_CLAMP    = {_pine_num(fus['score_clamp'])}")
    a(f"FM_FUSE_ALIGNEPS = {_pine_num(fus['align_eps'])}")
    a(f"FM_FUSE_Z        = {_pine_num(fus['credible_z'])}")
    a(f"FM_ISO_ON        = {str(bool(fus['isotonic_enabled'])).lower()}")
    a(f'FM_ISO_X         = "{_pine_csv(fus["knots_x"])}"')
    a(f'FM_ISO_Y         = "{_pine_csv(fus["knots_y"])}"')
    a("")
    a("// --- Edge Book posteriors (THEORY 7.3), one entry per cell -----------")
    a("// idx = (regime * n_setups + setup) * n_buckets + bucket")
    a(f"FM_EB_NSETUP     = {int(eb['n_setups'])}")
    a(f"FM_EB_NBUCKET    = {int(eb['n_buckets'])}")
    a(f'FM_EB_EDGES      = "{_pine_csv(eb["bucket_edges"])}"')
    a(f"FM_EB_Q          = {_pine_num(eb['lcb_quantile'])}")
    a(f'FM_EB_MU         = "{_pine_csv(cells["mu_n"])}"')
    a(f'FM_EB_SCALE      = "{_pine_csv(cells["scale"])}"')
    a(f'FM_EB_DOF        = "{_pine_csv(cells["dof"])}"')
    a(f'FM_EB_NEFF       = "{_pine_csv(cells["n_eff"])}"')
    a(f'FM_EB_OVAR       = "{_pine_csv(cells["outcome_var"])}"')
    a(f'FM_EB_VARMU      = "{_pine_csv(cells["var_mean"])}"')
    a("")
    a("// --- barriers, costs, gate, risk -------------------------------------")
    a(f"FM_STOP_SIGMA    = {_pine_num(ba['stop_sigma'])}")
    a(f"FM_TGT_SIGMA     = {_pine_num(ba['target_sigma'])}")
    a(f"FM_MAX_HOLD      = {int(ba['max_holding_bars'])}")
    a(f"FM_MIN_HOLD      = {int(ba['min_holding_bars'])}")
    a(f"FM_EXEC_LAG      = {int(ba['execution_lag_bars'])}")
    a(f"FM_COST_ETA      = {_pine_num(co['impact_eta'])}")
    a(f"FM_COST_PHI      = {_pine_num(co['slippage_range_frac'])}")
    a(f"FM_COST_FEE_BPS  = {_pine_num(co['fee_bps'])}")
    a(f"FM_COST_Q        = {_pine_num(co['default_participation'])}")
    a(f"FM_COST_MAXHS    = {_pine_num(co['max_half_spread_sigma'])}")
    a(f"FM_COST_SFALL    = {_pine_num(co['spread_fallback_rel'])}")
    a(f"FM_GATE_EVLCB    = {_pine_num(ga['ev_lcb_min_sigma'])}")
    a(f"FM_GATE_PMIN     = {_pine_num(ga['p_min'])}")
    a(f"FM_GATE_PEXIT    = {_pine_num(ga['p_exit'])}")
    a(f"FM_GATE_EBEMIN   = {_pine_num(ga['ebe_min'])}")
    a(f"FM_GATE_HAZMAX   = {_pine_num(ga['regime_hazard_max'])}")
    a(f"FM_GATE_RATE     = {_pine_num(ga['max_trades_per_100_bars'])}")
    a(f"FM_KELLY_FRAC    = {_pine_num(ri['kelly_fraction'])}")
    a(f"FM_RISK_BASE     = {_pine_num(ri['risk_per_trade'])}")
    a(f"FM_RISK_MAX      = {_pine_num(ri['max_risk_per_trade'])}")
    a(f"FM_DD_START      = {_pine_num(ri['dd_throttle_start'])}")
    a(f"FM_DD_STOP       = {_pine_num(ri['dd_throttle_stop'])}")
    a(f"FM_DD_FLOOR      = {_pine_num(ri['dd_throttle_floor'])}")
    a(f"FM_DD_KILL       = {_pine_num(ri['dd_kill'])}")
    a(PINE_END_MARKER)
    return "\n".join(L)


def emit_pine_constants(model: dict[str, Any] | str | Path, *pine_paths: str | Path) -> list[Path]:
    """Rewrite the ``BEGIN/END FROZEN MODEL`` region of each ``.pine`` file.

    The region is replaced wholesale, so the generated block is never merged
    with hand edits -- which is the point: a Pine script whose constants have
    been touched by hand no longer corresponds to any manifest hash.
    """
    if isinstance(model, (str, Path)):
        model = json.loads(Path(model).read_text(encoding="utf-8"))
    region = _pine_region(model)  # type: ignore[arg-type]
    pattern = re.compile(
        re.escape(PINE_BEGIN_MARKER) + r".*?" + re.escape(PINE_END_MARKER),
        re.DOTALL,
    )
    written: list[Path] = []
    for pp in pine_paths:
        p = Path(pp)
        text = p.read_text(encoding="utf-8")
        if not pattern.search(text):
            raise ValueError(f"{p} has no BEGIN/END FROZEN MODEL region")
        p.write_text(pattern.sub(lambda _m: region, text, count=1), encoding="utf-8")
        written.append(p)
    return written


# ---------------------------------------------------------------------------
# Reference training run
# ---------------------------------------------------------------------------


def train_reference_system(
    n_instruments: int = 6,
    n_bars: int = 9000,
    seed0: int = 1,
    cfg: Config | None = None,
) -> tuple[Any, dict[str, Any], dict[str, Any], tuple[float, float, int], np.ndarray]:
    """Train one Edge Book and one calibrator across a synthetic universe.

    This is the smallest honest instantiation of ``docs/01-THEORY.md`` §12:
    selectivity is applied per instrument, statistical power comes from pooling
    across instruments. A single series produces far too few trades for any of
    the exported posteriors to mean anything, and the exporter should not
    pretend otherwise -- so the default is a universe, not a symbol.

    The instruments are :func:`tia.synthetic.generate_with_regimes`, which is a
    *recovery* fixture, not a market. The numbers this produces are real in the
    sense that they came from the real training code; they are not real in the
    sense of describing any traded instrument. Re-run against the development
    universe before trading anything.
    """
    from .features.rolling import RollingCorrelation
    from .labeling.triple_barrier import apply_triple_barrier_to_bars
    from .labeling.weights import combined_weights
    from .pipeline import TIA
    from .synthetic import generate_with_regimes
    from .training import collect_candidates

    cfg = cfg or Config()
    book = EdgeBook(cfg)
    all_p: list[float] = []
    all_y: list[float] = []
    all_w: list[float] = []
    per_symbol: list[dict[str, Any]] = []
    longest: list[Any] = []

    for k in range(n_instruments):
        bars, _truth = generate_with_regimes(n=n_bars, seed=seed0 + k)
        if len(bars) > len(longest):
            longest = bars
        cands = collect_candidates(bars, cfg)
        arr = cands.arrays()
        if len(cands) == 0:
            per_symbol.append({"seed": seed0 + k, "n_bars": len(bars), "n_candidates": 0})
            continue
        res = apply_triple_barrier_to_bars(
            bars,
            entry_indices=arr["index"],
            directions=arr["direction"],
            stop_sigma=arr["stop_sigma"],
            target_sigma=arr["target_sigma"],
            sigma=arr["sigma"],
            max_holding=arr["max_holding"],
            execution_lag=cfg.execution_lag_bars,
        )
        w = combined_weights(
            n_bars=len(bars),
            entry_indices=res.entry_index,
            exit_indices=res.exit_index,
            halflife_bars=cfg.edge_halflife_bars,
        )
        ok = np.isfinite(res.ret_sigma)
        for j in np.nonzero(ok)[0]:
            book.observe(
                int(arr["regime"][j]),
                int(arr["setup"][j]),
                int(arr["bucket"][j]),
                float(res.ret_sigma[j]),
                weight=float(w[j]),
            )
        all_p.extend(arr["p_success"][ok].tolist())
        all_y.extend((res.outcome[ok] > 0).astype(float).tolist())
        all_w.extend(w[ok].tolist())
        per_symbol.append(
            {
                "seed": seed0 + k,
                "n_bars": len(bars),
                "n_candidates": int(len(cands)),
                "eligibility_rate": _r(cands.eligibility_rate),
                "hit_rate": _r(float((res.outcome[ok] > 0).mean())) if ok.any() else None,
                "mean_ret_sigma": _r(float(np.average(res.ret_sigma[ok], weights=w[ok]))) if ok.any() else None,
            }
        )

    cal = IsotonicCalibrator()
    if len(all_p) >= cfg.calibration_min_samples:
        cal.fit(np.array(all_p), np.array(all_y), weights=np.array(all_w))

    # Replay one instrument so the engine correlation estimator and the regime
    # tempering exponent hold measured values rather than their cold-start
    # priors. `learn=False` keeps the replay from adding to the pooled book.
    system = TIA(cfg, edge_book=book, learn=False)
    system.calibrator._iso = cal
    system.calibrator.active = cal.n_fit > 0
    # CALOP.observe() only feeds its estimator on bars where every engine in the
    # system is valid, and `crossasset`/`positioning` never are without
    # exogenous data -- so the system's own matrix would stay at its cold-start
    # prior forever. Estimate the ported engines' correlation directly, with the
    # same exponentially-weighted recursion CALOP uses.
    corr = RollingCorrelation(len(PINE_ENGINE_ORDER), halflife=float(cfg.correlation_window) / 2.0)
    tempers: list[float] = []
    for bar in longest:
        dec = system.on_bar(bar)
        t = float(system.regime_engine.state.temper)
        if math.isfinite(t) and system.kernel.snapshot.valid:
            tempers.append(t)
        outs = dec.engine_outputs
        vals = [outs[n].score if (n in outs and outs[n].valid) else math.nan for n in PINE_ENGINE_ORDER]
        if all(v == v for v in vals):
            corr.update(np.array(vals))

    t_arr = np.array(tempers) if tempers else np.array([1.0])
    tempering = (float(np.median(t_arr)), float(np.std(t_arr)), int(t_arr.size))
    if corr.count > 60:
        c_eng = corr.correlation(ridge=cfg.fusion_shrink)
        corr_source = (
            f"exponentially-weighted rolling correlation of the {len(PINE_ENGINE_ORDER)} "
            f"ported engine scores over {corr.count} bars, ridge {cfg.fusion_shrink}"
        )
    else:  # pragma: no cover - only on a pathologically short replay
        c_eng = np.full((len(PINE_ENGINE_ORDER),) * 2, 0.35)
        np.fill_diagonal(c_eng, 1.0)
        c_eng = (1.0 - cfg.fusion_shrink) * c_eng + cfg.fusion_shrink * np.eye(len(PINE_ENGINE_ORDER))
        corr_source = "CALOP cold-start prior (0.35 everywhere): replay too short to measure"

    dev_universe = {
        "kind": "synthetic",
        "generator": "tia.synthetic.generate_with_regimes",
        "n_instruments": n_instruments,
        "bars_per_instrument": n_bars,
        "seeds": [seed0 + k for k in range(n_instruments)],
        "warning": (
            "Synthetic recovery fixture, not a market. Re-run against the "
            "development universe of docs/00-PREREGISTRATION.md before trading."
        ),
        "per_symbol": per_symbol,
    }
    training = {
        "n_outcomes": len(all_p),
        "hit_rate": _r(float(np.mean(all_y))) if all_y else None,
        "isotonic_fitted": bool(cal.n_fit > 0),
        "isotonic_n_fit": int(cal.n_fit),
        "correlation_samples": _r(float(system.calop.diagnostics()["samples"])),
        "engine_mean_abs_corr": _r(float(system.calop.diagnostics()["mean_abs_corr"])),
        "replay_bars": len(longest),
    }
    return system, dev_universe, training, tempering


def main(argv: Sequence[str] | None = None) -> int:  # pragma: no cover - CLI
    import argparse

    ap = argparse.ArgumentParser(description="Freeze a trained TI-A for the Pine port.")
    # Repo-relative, not cwd-relative: running `python -m tia.export` from
    # python/ previously wrote a stray python/pine/ tree.
    _repo = pathlib.Path(__file__).resolve().parents[3]
    ap.add_argument("--out", default=str(_repo / "pine" / "frozen_model.json"))
    # Emitting is the DEFAULT, not an opt-in. A JSON manifest that has been
    # regenerated while the .pine files still carry the previous constants is
    # the worst of both worlds: the audit passes on the JSON, the chart runs the
    # old model, and nothing anywhere says so. This exact divergence shipped
    # once -- the Pine files kept a pre-fix isotonic map asserting 0% and 100%
    # confidence for a full commit. Use --no-emit to suppress deliberately.
    _pine = sorted((_repo / "pine").glob("*.pine"))
    ap.add_argument(
        "--emit", nargs="*", default=[str(x) for x in _pine],
        help=".pine files whose frozen region to rewrite (default: all of pine/*.pine)",
    )
    ap.add_argument("--no-emit", action="store_true", help="write the JSON only")
    ap.add_argument("--instruments", type=int, default=6)
    ap.add_argument("--bars", type=int, default=9000)
    ap.add_argument("--seed", type=int, default=1)
    ns = ap.parse_args(argv)

    system, dev, train, temper = train_reference_system(ns.instruments, ns.bars, ns.seed)
    model = export_frozen_model(
        system, ns.out, dev_universe=dev, training=train, tempering=temper
    )
    emitted: list[pathlib.Path] = []
    if ns.emit and not ns.no_emit:
        emitted = emit_pine_constants(model, *ns.emit)
    if emitted:
        print("emitted constants into " + ", ".join(p.name for p in emitted))
    elif not ns.no_emit:
        print("WARNING: no .pine files found to emit into", file=sys.stderr)
    print(
        f"wrote {ns.out}  schema={model['schema_version']}  "
        f"manifest={model['config_manifest_hash']}  "
        f"cells={model['edge_book']['n_cells']}  "
        f"outcomes={model['fusion']['n_outcomes']}  "
        f"isotonic={'on' if model['fusion']['isotonic_enabled'] else 'off'}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
